version: '{build}'
os: Visual Studio 2017
branches:
  only:
  - master
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
skip_commits:
  files:
    - docs/*
    - LICENSE
    - README.md
    - .travis.yml
    - .gitignore
build_script:
- ps: ./build.ps1
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: /gak8VxtAbZvOTqON513KwsK5BtDUmoPjjzCMu+tn2i+vkupZbjnIKq/XnP4GGgv
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
  on:
    branch: master